# Generated by Django 3.2.15 on 2022-10-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientcomment',
            fields=[
                ('seq', models.AutoField(db_column='SEQ', primary_key=True, serialize=False)),
                ('newseq', models.IntegerField(blank=True, db_column='NEWSEQ', null=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=150, null=True)),
                ('text', models.CharField(blank=True, db_column='TEXT', max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ClientComment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('seq', models.AutoField(db_column='SEQ', primary_key=True, serialize=False)),
                ('occr_dt', models.CharField(db_collation='utf8_general_ci', db_column='OCCR_DT', max_length=8)),
                ('occr_loc', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='OCCR_LOC', max_length=200, null=True)),
                ('title', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='TITLE', max_length=50, null=True)),
                ('url', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='URL', max_length=200, null=True)),
                ('text', models.CharField(blank=True, db_column='TEXT', max_length=10000, null=True)),
                ('anal_yn', models.CharField(blank=True, db_column='ANAL_YN', max_length=1, null=True)),
                ('extr_yn', models.CharField(blank=True, db_column='EXTR_YN', max_length=1, null=True)),
                ('extr_stck_cd_list', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='EXTR_STCK_CD_LIST', max_length=500, null=True)),
                ('img_url_list', models.CharField(blank=True, db_column='IMG_URL_LIST', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'NEWS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('market', models.CharField(db_column='Market', max_length=6, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_column='Symbol', max_length=6)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=20, null=True)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=20, null=True)),
                ('listingdate', models.CharField(blank=True, db_column='ListingDate', max_length=8, null=True)),
                ('settlemonth', models.CharField(blank=True, db_column='SettleMonth', max_length=2, null=True)),
                ('representative', models.CharField(blank=True, db_column='Representative', max_length=30, null=True)),
                ('homepage', models.CharField(blank=True, db_column='HomePage', max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=200, null=True)),
            ],
            options={
                'db_table': 'STOCKS',
                'managed': False,
            },
        ),
    ]
