# Generated by Django 3.2.15 on 2022-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientheart',
            fields=[
                ('clientid', models.IntegerField(db_column='ClientId', primary_key=True, serialize=False)),
                ('newsseq', models.IntegerField(db_column='NewsSeq')),
            ],
            options={
                'db_table': 'ClientHeart',
                'managed': False,
            },
        ),
    ]
