# Generated by Django 3.2.15 on 2022-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedApp', '0002_clientheart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientfollowstock',
            fields=[
                ('seq', models.AutoField(db_column='Seq', primary_key=True, serialize=False)),
                ('clientid', models.IntegerField(db_column='ClientId')),
                ('market', models.CharField(blank=True, db_column='Market', max_length=6, null=True)),
                ('symbol', models.CharField(blank=True, db_column='Symbol', max_length=6, null=True)),
            ],
            options={
                'db_table': 'ClientFollowStock',
                'managed': False,
            },
        ),
    ]
